# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_AVIRT_AP_LOOPBACK) += snd-avirt-ap-loopback.o

$(info $(src))
snd-avirt-ap-loopback-objs := loopback.o
ccflags-y += -Idrivers/staging/
ccflags-y += -I$(src)/../
